### PR TITLE
simplify extractCString

### PR DESCRIPTION
**Pull request by tathanhdinh**
Hello all,

This PR simplifies the implementation of `extractCString`.

Thanks a lot for any comment.

### CODE REVIEW

**Comment by sangkilc** [comment]
Thank you for your PR. Your patch seems indeed much concise and easy to read.

However, a simple test reveals that the performance of the patched version is unacceptably slow (x400 slower on my machine):

```fsharp
open System
open System.Text

let extractCString1 bytes offset =
  let rec loop (acc: StringBuilder) offset =
    match Array.get bytes offset with
    | 0uy -> acc.ToString ()
    | b -> loop (char b |> acc.Append) (offset + 1)
  if bytes.Length = 0 then "" else loop (StringBuilder()) offset

let extractCString2 (bytes: byte[]) offset =
  Array.findIndex ((=) 0uy) bytes.[offset..]
  |> fun i -> Array.sub bytes offset i
  |> Array.map char
  |> String

let bs = System.IO.File.ReadAllBytes ("/bin/ls") // you can replace this with any binary file.

#time
let main =
  [0 .. bs.Length - 1]
  |> List.iter (fun i -> extractCString1 bs i |> ignore)
#time

#time
let main =
  [0 .. bs.Length - 1]
  |> List.iter (fun i -> extractCString2 bs i |> ignore)
#time

/// Result:
Real: 00:00:00.043, CPU: 00:00:00.044, GC gen0: 12, gen1: 0
Real: 00:00:18.598, CPU: 00:00:19.411, GC gen0: 9, gen1: 345
```

I think this is due to several problems:
(1) Array.map involves unnecessary iteration on the array.
(2) The conversion from byte to char results in unnecessary memory chunks for gc.

One of the key design principles of B2R2 is being fast even if the code looks a bit ugly. Even though the "core code" is a bit ugly, we can write an elegant analyzer with F# anyways.

**Comment by tathanhdinh** [comment]
Many thanks.

I think I should learn more about .NET performance :(

Your time evaluation is correct, this version is much much slower than yours. Beside the problems you have listed, I may think of several reasons more:

- array slicing needs to create a new array
- my version needs traversing 3 times the array (while yours needs only 1)
- `StringBuilder`is a mutable-by-design string class

If the key design principle is to make B2R2 is fast, I believe that the following version of `extractCString` is even faster than the current one:

```F#
let extractCString (bytes: _ []) offset =
  let acc = StringBuilder ()
  let mutable i = offset
  while bytes.[i] <> 0uy do
    acc.Append (char bytes.[i]) |> ignore
    i <- i + 1
  acc.ToString ()
```

I evaluate it on my machine, it's at least two times faster (the testcase is "/bin/ls").

**Comment by sangkilc** [comment]
Interesting, the mutable version seems equivalent to the current version to me with tail-call optimization, and I don't understand why the mutable version will be faster. I think you'd better check if you have run your test with tail-call optimization enabled.

On my machine, the performance of the mutable version and the current B2R2's version is more or less the same, and I don't think we prefer "mutable version" in general unless it is strikingly faster 😄

**Comment by sangkilc** [comment]
FYI, this is the result on my machine:

Current B2R2's version with `/bin/ls` three times:
```
$ fsharpi comp.fsx
Real: 00:00:00.044, CPU: 00:00:00.045, GC gen0: 11, gen1: 0
Real: 00:00:00.042, CPU: 00:00:00.042, GC gen0: 11, gen1: 0
Real: 00:00:00.043, CPU: 00:00:00.043, GC gen0: 12, gen1: 0
```

The mutable version:
```
$ fsharpi comp.fsx
Real: 00:00:00.047, CPU: 00:00:00.048, GC gen0: 11, gen1: 0
Real: 00:00:00.043, CPU: 00:00:00.043, GC gen0: 11, gen1: 0
Real: 00:00:00.043, CPU: 00:00:00.043, GC gen0: 12, gen1: 0
```

Seems totally the same to me in terms of both speed and the GC.

**Comment by tathanhdinh** [comment]
Cannot find any better implementation, I abandon the PR :).

**Pull request closed without merging**
