### PR TITLE
Reformatted code in order to follow official F# coding style

### PR DESCRIPTION
**Pull request by enkomio**
The project use a 2 spaces indentation, this is an uncommon choice and also a not recommended one according to the following sources:
* Stylish F#: Crafting Elegant Functional Code for .NET and .NET Core
* <a href="https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting">F# code formatting guidelines</a>

By using 4 spaces for indentation it will be easier to contribute from developers that use more common F# IDE, like Visual Studio and Visual Studio Code.

I wrote a simple program to adjust the indentation and then fixed the few compiling errors.

### CODE REVIEW

**Comment by sangkilc** [comment]
Thank you for creating this PR.

I understand that the default choice for visual studio is 4 spaces. But from the link that you provide it also says:
> That said, indentation of programs is a subjective matter. Variations are OK, but the first rule you should follow is consistency of indentation. Choose a generally accepted style of indentation and use it systematically throughout your codebase.

We really think that modifying the visual studio setting is a trivial matter and it will not prevent programmers from contributing to this project. And I personally think that column width of 80 chars is too harsh when we use 4 spaces for indentation. If we increase the max column width, then it will be okay to use 4 spaces, but I strongly believe in the [eighty column rule](https://www.emacswiki.org/emacs/EightyColumnRule). That's the reason why we follow OCaml's style (2 spaces for indentation + max 80 column).

Nevertheless, we will think about this issue carefully, and will adapt our coding style if necessary. Will be happy to get more inputs on this matter.

**Comment by enkomio** [comment]
Thanks for the answer. 

Indeed, modifying the Visual Studio settings is very easy. The annoying fact is that it is a global settings and not a project settings. This means that every time that we switch to another project we have to change the settings back.

I understand the 80 columns rule (even if in my opinion it is a bit obsolete ^^) and I think that it is not difficult to satisfy it even with 4 spaces indentation (most of my manual fixes were done by just inserting a newline in order to break the line).

I consider this project very interesting and it is for this reason that I think that following the rules suggested by MS would be of great benefit for the code.

Whatever will be your final decision I would love to contribute to it (in my daily work I'm mainly involved in malware analysis) :)

P.S.
as you might guess I'm more a Windows developer but on the Linux side I see that Linus proposes to use 8 spaces for tab in this old post  https://public-inbox.org/git/alpine.LFD.0.999.0710161722320.26902@woody.linux-foundation.org/ (I'm joking here :P)

**Comment by tathanhdinh** [comment]
I would prefer 4 spaces indentation too. It seems to me that `vscode` detects the indentation automatically, so when I open B2R2, the indentation changes automagically into 2 (!?).

**Comment by sangkilc** [comment]
Thank you all for your comments.

In fact, Visual Studio and Visual Studio Code support per-solution config.
- https://devblogs.microsoft.com/dotnet/code-style-configuration-in-the-vs2017-rc-update/
- https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

Furthermore, there is well-known F# projects that use 2-space indentation, such as https://github.com/SuaveIO/suave

So we decided not to change our formatting rule. However, we will update the [editorconfig file](https://github.com/B2R2-org/B2R2/blob/master/.editorconfig) so that your visual studio can automatically change settings for B2R2 project. This will make all of us happy I believe 😄What do you think?

**Comment by sangkilc** [comment]
Updated the editorconfig file, not tested though.

**Comment by enkomio** [comment]
I only tested the configuration through the VS interface. By using the new _editorconfig_ file it works as you specified.

In the end, no problem in using a 2 spaces indentation. Since the _editorconfig_ resolve the switching problem I think that this PR can be closed.

**Pull request closed without merging**
